### PR TITLE
intoroduced layoutAsync options

### PR DESCRIPTION
**Pull request by IvanKalinin**
Introduced a new configuration option **layoutAsync** that allows you to create a custom layout asynchronously.

Very useful if you need to include attachments (such as screenshots of failures) to the array on Slack blocks, uploading them somewhere.

### CODE REVIEW

**Comment by ryanrosello-og** [comment]
hey @IvanKalinin , thanks for your contribution.  Would you mind providing an example in the readme to demonstrate how we can include attachments?  Also, would the existing bots require to elevated privileges to do this?

**Comment by IvanKalinin** [comment]
@ryanrosello-og ,
I've added an example in README.md.

Since I've introduced a new parameter it is not a breaking change for existing users and bots. Also, I didn't make any changes to the default layout generator.

Also, it is not necessary to upload the assets in slack. You can upload them to any service of your choice. I upload them to the S3 bucket and included the snippet in the example.

**Comment by ryanrosello-og** [comment]
thanks @IvanKalinin, was about to merge but seems to be failing on lint.

**Comment by IvanKalinin** [comment]
@ryanrosello-og For now reverted TS annotations to what it was before.
Improving types might be a good idea for the next PR

**Comment by IvanKalinin** [comment]
@ryanrosello-og I believe it should be good to go

**Comment by ryanrosello-og** [comment]
thanks @IvanKalinin all merged and released in v1.0.20

**Pull request merged**
