### PR TITLE
separate flaky tests from output - passes that did not pass on first try are instead output as flaky, not passed

### PR DESCRIPTION
**Pull request by jgibo**
Conditionally enabled by config option `separateFlaky` of type boolean. Default is false, which will not change the current behaviour.

### CODE REVIEW

**Comment by jgibo** [comment]
There seems to be some conflict with the prettier and eslint rules. Running `npm run prettier` then results in some eslint failures.

I ran the prettier fmt in a separate commit, so luckily I can revert easily if necessaru. lmk if you want to adjust this to use eslint instead or just ignore.

**Comment by ryanrosello-og** [comment]
Very nice 🚀  @jgibo , thank you for fixing this

**Comment by ryanrosello-og** [comment]
hmm, yeah eslint is being a pain here => https://github.com/ryanrosello-og/playwright-slack-report/actions/runs/6275837955/job/17058601126?pr=54

Leave it with me and I will fix when i do the version bump

**Comment by jgibo** [comment]
Thanks @ryanrosello-og! Great lib you've built here.

I'm also looking into the issue where the statistics count doesn't seem to be right in certain environments. At my job, we're running the tests in a GCP VM and the counts appear to be off in the stats output - different to what playwright reports in the suite end logs.

Seems strange that the runtime env would affect this, hopefully I'll know more about this later today then I'll report back.

**Pull request merged**
